Fix for ficus
raccoongang/rg_instructor_analytics pull request #9
Opened 2018-01-09 17:51 UTC by flying-pi

2018-01-10 09:18 UTC, alexbojko requested changes

2018-01-10 09:18 UTC, alexbojko commented on rg_instructor_analytics/views.py
> +from web_fragments.views import FragmentView
ditto

2018-01-10 09:18 UTC, alexbojko commented on rg_instructor_analytics/views.py
> +
pls order imports according to these rules https://www.python.org/dev/peps/pep-0008/#imports

2018-01-10 09:18 UTC, alexbojko commented on rg_instructor_analytics/plugins.py
> +        """
ditto

2018-01-10 09:18 UTC, alexbojko commented on rg_instructor_analytics/plugins.py
> +    def fragment_view(self):
one line pls

2018-01-10 09:18 UTC, alexbojko commented on rg_instructor_analytics/plugins.py
> +        return "tab/" + self.type
probably it should be better to use ```"tab/{}".format(self.type)```

2018-01-10 09:18 UTC, alexbojko commented on rg_instructor_analytics/plugins.py
> +        """
same as above

2018-01-10 09:18 UTC, alexbojko commented on rg_instructor_analytics/plugins.py
>      """
one line comment should be fit in one line

2018-01-10 09:18 UTC, alexbojko commented on rg_instructor_analytics/plugins.py
> +        Counstruct tab.
one line pls

2018-01-10 09:18 UTC, alexbojko commented on rg_instructor_analytics/plugins.py
>          """
one line please

2018-01-10 09:18 UTC, alexbojko commented on rg_instructor_analytics/plugins.py
> +        return "tab/" + self.type
my proposition to use "tab/{}".format(self.type)

2018-01-10 09:27 UTC, flying-pi commented on rg_instructor_analytics/plugins.py
>          """
According to style guide http://edx.readthedocs.io/projects/edx-developer-guide/en/latest/style_guides/python-guidelines.html, we use multiline style

2018-01-10 09:27 UTC, flying-pi commented on rg_instructor_analytics/plugins.py
> +        Counstruct tab.
ditto

2018-01-10 09:27 UTC, flying-pi commented on rg_instructor_analytics/plugins.py
> +        """
ditto

2018-01-10 09:29 UTC, flying-pi commented on rg_instructor_analytics/plugins.py
> +        return "tab/" + self.type
Thank, I fixed it.

2018-01-10 09:29 UTC, flying-pi commented on rg_instructor_analytics/plugins.py
> +    def fragment_view(self):
ditto

2018-01-10 09:29 UTC, flying-pi commented on rg_instructor_analytics/plugins.py
> +        """
ditto

2018-01-10 11:50 UTC, alexbojko commented on rg_instructor_analytics/plugins.py
>          """
ok, let it be

2018-01-10 11:55 UTC, alexbojko commented on README.md
> +* Add `rg_instructor_analytics` and `web_fragments` to the installed app (i.e. in `edx-platform/lms/envs/common.py`)
maybe you meant INSTALLED_APPS instead of installed app?

2018-01-10 11:55 UTC, alexbojko commented on rg_instructor_analytics/plugins.py
> +        """
thank you for this fix!

2018-01-11 12:50 UTC, alexbojko approved these changes

2018-01-11 12:51 UTC, merged